/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gpac_Osmo4_Decoder */

#ifndef _Included_com_gpac_Osmo4_Decoder
#define _Included_com_gpac_Osmo4_Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gpac_Osmo4_Decoder
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gpac_Osmo4_Decoder_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gpac_Osmo4_Decoder
 * Method:    setPlaying
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gpac_Osmo4_Decoder_setPlaying
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_gpac_Osmo4_Decoder
 * Method:    setSurface
 * Signature: (Landroid/view/Surface;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gpac_Osmo4_Decoder_setSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_gpac_Osmo4_Decoder
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gpac_Osmo4_Decoder_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
